//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIAB_Restaurent_Management_System.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class financetransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public financetransaction()
        {
            this.salepurchaseproduct = new HashSet<salepurchaseproduct>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> amount { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string paymentmethod { get; set; }
        public string referencenumber { get; set; }
        public string bank { get; set; }
        public string branch { get; set; }
        public Nullable<System.DateTime> chequedate { get; set; }
        public string details { get; set; }
        public Nullable<int> fk_createdbyuser_user_financetransaction { get; set; }
        public Nullable<int> fk_targettouser_user_financetransaction { get; set; }
        public Nullable<int> fk_financeaccount_financeaccount_financetransaction { get; set; }
    
        public virtual financeaccount financeaccount { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salepurchaseproduct> salepurchaseproduct { get; set; }
        public virtual user user1 { get; set; }
    }
}
