//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIAB_Restaurent_Management_System.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbctx : DbContext
    {
        public dbctx()
            : base("name=dbctx")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<closing> closing { get; set; }
        public virtual DbSet<financeaccount> financeaccount { get; set; }
        public virtual DbSet<financetransaction> financetransaction { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<salepurchaseproduct> salepurchaseproduct { get; set; }
        public virtual DbSet<subproduct> subproduct { get; set; }
        public virtual DbSet<tbl_FinanceChart> tbl_FinanceChart { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
