//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIAB_Restaurent_Management_System.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class subproduct
    {
        public int id { get; set; }
        public Nullable<int> fk_product_product_subproduct { get; set; }
        public Nullable<int> fk_subproduct_product_subproduct { get; set; }
        public Nullable<double> quantity { get; set; }
    
        public virtual product product { get; set; }
        public virtual product product1 { get; set; }
    }
}
